// Code generated by nvault-schemagen. DO NOT EDIT.
// Mirrors the public Go wire contract in wire and crypto.

export type Kind = "secret" | "param";

export type ValueType = "string" | "int" | "bool" | "json";

export const ENVELOPE_FORMAT_V1 = "nvault.enc.v1";
export const ENVELOPE_ALG_V1 = "x25519-xchacha20poly1305";

/** A unified secret or parameter entry. Mirrors wire.Item. */
export interface Item {
  key: string;
  kind: Kind;
  scope: string;
  /** params only */
  type?: ValueType;
  /** empty for secrets in listings */
  value?: string;
  /** params only */
  version?: number;
  updated_at?: string;
  has_value: boolean;
}

/** One recipient's wrapped copy of the data key. Mirrors crypto.Stanza. */
export interface Stanza {
  recipient_id: string;
  /** base64 (Go []byte JSON encoding) of the NaCl sealed-box wrapped DEK */
  wrapped_key: string;
}

/** The end-to-end-encrypted payload. Mirrors crypto.Envelope. */
export interface Envelope {
  v: string;
  alg: string;
  /** base64 (Go []byte JSON encoding) */
  nonce: string;
  /** base64 (Go []byte JSON encoding) */
  ciphertext: string;
  recipients: Stanza[];
  aad?: string;
}

/** A labeled X25519 public key. Mirrors crypto.Recipient. */
export interface Recipient {
  id: string;
  public_key: string;
}

/** One item on the wire to/from the cloud /sync API. */
export interface WireItem {
  key: string;
  kind: Kind;
  ciphertext: string;
  version: number;
}

/** One compare-and-swap item in a POST /sync/push request. */
export interface PushItem {
  key: string;
  kind: Kind;
  ciphertext: string;
  expected_version: number;
}

/** POST /sync/push body. */
export interface PushRequest {
  org: string;
  env: string;
  scope: string;
  recipient_revision: number;
  items: PushItem[];
}

/** POST /sync/push response. */
export interface PushResponse {
  results: { key: string; version: number }[];
}

/** GET /sync/pull response. */
export interface PullResponse {
  items: WireItem[];
  recipient_revision: number;
  cursor: string | null;
  done: boolean;
}

/** GET /sync/policy response. Public encryption metadata only. */
export interface RecipientPolicyResponse {
  recipient_revision: number;
  recipients: Recipient[];
}

/** POST /sync/versions request and response. */
export interface VersionsRequest {
  org: string;
  env: string;
  scope: string;
  keys: string[];
}

export interface VersionsResponse {
  results: { key: string; version: number; deleted: boolean }[];
}

/** POST /sync/delete request and response. */
export interface DeleteRequest {
  org: string;
  env: string;
  scope: string;
  key: string;
  expected_version: number;
}

export interface DeleteResponse {
  key: string;
  version: number;
  deleted: true;
}
