// Command nvault-schemagen emits the TypeScript declarations for nvault's Go
// wire contract.
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/nstranquist/nvault/crypto"
	"github.com/nstranquist/nvault/wire"
)

func main() {
	output := render()
	args := os.Args[1:]
	if len(args) > 0 && args[0] == "--check" {
		if len(args) != 2 {
			fmt.Fprintln(os.Stderr, "nvault-schemagen: --check requires one path")
			os.Exit(2)
		}
		existing, err := os.ReadFile(args[1])
		if err != nil {
			fmt.Fprintf(os.Stderr, "nvault-schemagen: read %s: %v\n", args[1], err)
			os.Exit(1)
		}
		if string(existing) != output {
			fmt.Fprintf(os.Stderr, "nvault-schemagen: %s is out of date\n", args[1])
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "nvault-schemagen: %s is up to date\n", args[1])
		return
	}
	if len(args) > 1 {
		fmt.Fprintln(os.Stderr, "nvault-schemagen: expected zero arguments or one output path")
		os.Exit(2)
	}
	if len(args) == 1 && args[0] != "-" {
		if err := os.WriteFile(args[0], []byte(output), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "nvault-schemagen:", err)
			os.Exit(1)
		}
		return
	}
	fmt.Print(output)
}

func render() string {
	var output strings.Builder
	output.WriteString("// Code generated by nvault-schemagen. DO NOT EDIT.\n")
	output.WriteString("// Mirrors the public Go wire contract in wire and crypto.\n\n")
	fmt.Fprintf(&output, "export type Kind = %q | %q;\n\n", wire.KindSecret, wire.KindParam)
	fmt.Fprintf(&output, "export type ValueType = %q | %q | %q | %q;\n\n", wire.TypeString, wire.TypeInt, wire.TypeBool, wire.TypeJSON)
	fmt.Fprintf(&output, "export const ENVELOPE_FORMAT_V1 = %q;\n", crypto.FormatV1)
	fmt.Fprintf(&output, "export const ENVELOPE_ALG_V1 = %q;\n\n", crypto.AlgV1)
	output.WriteString(`/** A unified secret or parameter entry. Mirrors wire.Item. */
export interface Item {
  key: string;
  kind: Kind;
  scope: string;
  /** params only */
  type?: ValueType;
  /** empty for secrets in listings */
  value?: string;
  /** params only */
  version?: number;
  updated_at?: string;
  has_value: boolean;
}

/** One recipient's wrapped copy of the data key. Mirrors crypto.Stanza. */
export interface Stanza {
  recipient_id: string;
  /** base64 (Go []byte JSON encoding) of the NaCl sealed-box wrapped DEK */
  wrapped_key: string;
}

/** The end-to-end-encrypted payload. Mirrors crypto.Envelope. */
export interface Envelope {
  v: string;
  alg: string;
  /** base64 (Go []byte JSON encoding) */
  nonce: string;
  /** base64 (Go []byte JSON encoding) */
  ciphertext: string;
  recipients: Stanza[];
  aad?: string;
}

/** A labeled X25519 public key. Mirrors crypto.Recipient. */
export interface Recipient {
  id: string;
  public_key: string;
}

/** One item on the wire to/from the cloud /sync API. */
export interface WireItem {
  key: string;
  kind: Kind;
  ciphertext: string;
  version: number;
}

/** One compare-and-swap item in a POST /sync/push request. */
export interface PushItem {
  key: string;
  kind: Kind;
  ciphertext: string;
  expected_version: number;
}

/** POST /sync/push body. */
export interface PushRequest {
  org: string;
  env: string;
  scope: string;
  recipient_revision: number;
  items: PushItem[];
}

/** POST /sync/push response. */
export interface PushResponse {
  results: { key: string; version: number }[];
}

/** GET /sync/pull response. */
export interface PullResponse {
  items: WireItem[];
  recipient_revision: number;
  cursor: string | null;
  done: boolean;
}

/** GET /sync/policy response. Public encryption metadata only. */
export interface RecipientPolicyResponse {
  recipient_revision: number;
  recipients: Recipient[];
}

/** POST /sync/versions request and response. */
export interface VersionsRequest {
  org: string;
  env: string;
  scope: string;
  keys: string[];
}

export interface VersionsResponse {
  results: { key: string; version: number; deleted: boolean }[];
}

/** POST /sync/delete request and response. */
export interface DeleteRequest {
  org: string;
  env: string;
  scope: string;
  key: string;
  expected_version: number;
}

export interface DeleteResponse {
  key: string;
  version: number;
  deleted: true;
}
`)
	return output.String()
}
